### PR TITLE
[FIX] Fixes memory leak

### PR DESCRIPTION
**Pull request by mcerman**
Around 1-2MB of CPU memory are being leaked per batch size of 4 at image size [1024, 1024]. This fixes the memory leak.

### CODE REVIEW

**Comment by Abdul-Mukit** [comment]
@mcerman I tried with the following changes:
```
total_loss = defaultdict(float)
total_loss[loss_name] += loss_val.item() * batch_size
```
Not only solves the memory issue but also decreases the overall memory consumption by 10GB for a batch size of [16, 3, 640, 640].

**Comment by Abdul-Mukit** [comment]
@mcerman thank you. I tried out the following variation to solve the leak.
```
total_loss = defaultdict(float)
total_loss[loss_name] += loss_val.item() * batch_size
```
[Reference.]( https://discuss.pytorch.org/t/automatic-conversion-to-tensors-may-cause-memory-leaks/20487)

Do you think `total_loss` should be a dict of tensor or float?
This was the original defintion: `total_loss = defaultdict(lambda: torch.tensor(0.0, device=self.device))`.
After `train_one_epoch` we just use this `total_loos` to log scalar values in:
https://github.com/WongKinYiu/YOLO/blob/8228669808a626fc5f9c233fdb35550b5e041fae/yolo/utils/logging_utils.py#L168
So I don't understand why we would make `total_loss` a Tensor on the `self.device`. 
Just trying to learn, Thank you.

**Comment by mcerman** [comment]
@Abdul-Mukit yeah, I think that your proposed solution is the preferred one - the `total_loss` is only being used for logging purposes, so having it defined your way is correct:

```
total_loss = defaultdict(float)
total_loss[loss_name] += loss_val.item() * batch_size
```

My primary intention was to bring it to attention, that this is the part that causes the memory leak, and that there is an easy fix. I'll change the pull request to your proposed code.

**Comment by henrytsui000** [comment]
Thank you, @mcerman, for your contribution, and @vlaminckaxel, @Abdul-Mukit  for your input. I will merge this PR after today's ECCV conference!

For consistency, if you could complete the checklist from the template, that would be great! (Please note that this repo is restricted to following the MIT license.)

Best regards,
Henry Tsui

**Comment by vlaminckaxel** [comment]
@henrytsui000 are you still at eccv and wasn't to meet?

**Comment by wep21** [comment]
memory leak still seems to exist in the latest branch

**Pull request merged**
